//
//  Quotes.swift
//  CultureCal
//
//  Created by Kelly Brown on 6/12/23.
//

import Foundation
import SwiftUI

struct Quote: Identifiable {
    let id = UUID()
    let text: String
    let author: String
    let imageName: String
    let additionalInfo: String
}
let quotes: [Quote] = [
    Quote(text: "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome while trying to succeed.", author: "Booker T. Washington", imageName: "booker_t_washington", additionalInfo: "Booker T. Washington was an African American educator, author, and leader of the late 19th and early 20th centuries."),
    Quote(text: "I refuse to accept the view that mankind is so tragically bound to the starless midnight of racism and war that the bright daybreak of peace and brotherhood can never become a reality.", author: "Martin Luther King Jr.", imageName: "martin_luther_king_jr", additionalInfo: "Martin Luther King Jr. was a prominent leader of the civil rights movement in the United States."),
    Quote(text: "If there is no struggle, there is no progress.", author: "Frederick Douglass", imageName: "frederick_douglass", additionalInfo: "Frederick Douglass was an African American social reformer, abolitionist, writer, and statesman."),
    Quote(text: "I am where I am because of the bridges that I crossed. Sojourner Truth was a bridge. Harriet Tubman was a bridge. Ida B. Wells was a bridge. Madame C.J. Walker was a bridge. Fannie Lou Hamer was a bridge.", author: "Oprah Winfrey", imageName: "oprah_winfrey", additionalInfo: "Oprah Winfrey is an American media executive, actress, talk show host, television producer, and philanthropist."),
    Quote(text: "Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly.", author: "Langston Hughes", imageName: "langston_hughes", additionalInfo: "Langston Hughes was an American poet, social activist, novelist, playwright, and columnist."),
    Quote(text: "The cost of liberty is less than the price of repression.", author: "W.E.B. Du Bois", imageName: "web_du_bois", additionalInfo: "W.E.B. Du Bois was an American sociologist, historian, civil rights activist, and author."),
    Quote(text: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr.", imageName: "martin_luther_king_jr", additionalInfo: "Martin Luther King Jr. was a prominent leader of the civil rights movement in the United States."),
    Quote(text: "Change will not come if we wait for some other person or some other time. We are the ones we've been waiting for. We are the change that we seek.", author: "Barack Obama", imageName: "barack_obama", additionalInfo: "Barack Obama was the 44th President of the United States."),
    Quote(text: "Every great dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.", author: "Harriet Tubman", imageName: "harriet_tubman", additionalInfo: "Harriet Tubman was an American abolitionist and political activist."),
    Quote(text: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.", author: "Martin Luther King Jr.", imageName: "martin_luther_king_jr", additionalInfo: "Martin Luther King Jr. was a prominent leader of the civil rights movement in the United States."),
    Quote(text: "The most common way people give up their power is by thinking they don't have any.", author: "Alice Walker", imageName: "alice_walker", additionalInfo: "Alice Walker is an American novelist, short story writer, poet, and social activist."),
    Quote(text: "In recognizing the humanity of our fellow beings, we pay ourselves the highest tribute.", author: "Thurgood Marshall", imageName: "thurgood_marshall", additionalInfo: "Thurgood Marshall was an American lawyer and civil rights activist who served as the first African American Associate Justice of the Supreme Court of the United States."),
    Quote(text: "Defining myself, as opposed to being defined by others, is one of the most difficult challenges I face.", author: "Carol Moseley Braun", imageName: "carol_moseley_braun", additionalInfo: "Carol Moseley Braun is an American diplomat, politician, and lawyer who served as the United States Senator from Illinois."),
    Quote(text: "The only way to deal with this life any way is to live every bit of it and take the laughs with the tears.", author: "Ruby Dee", imageName: "ruby_dee", additionalInfo: "Ruby Dee was an American actress, poet, playwright, screenwriter, journalist, and civil rights activist."),
    Quote(text: "If you want to fly, you have to give up the things that weigh you down.", author: "Toni Morrison", imageName: "toni_morrison", additionalInfo: "Toni Morrison was an American novelist, essayist, editor, teacher, and professor emeritus at Princeton University."),
    Quote(text: "The battles that count aren't the ones for gold medals. The struggles within yourself—the invisible, inevitable battles inside all of us—that's where it's at.", author: "Jesse Owens", imageName: "jesse_owens", additionalInfo: "Jesse Owens was an American track and field athlete who specialized in sprinting and long jump."),
    Quote(text: "I had to make my own living and my own opportunity! But I made it! Don't sit down and wait for the opportunities to come. Get up and make them!", author: "Madam C.J. Walker", imageName: "madam_cj_walker", additionalInfo: "Madam C.J. Walker was an American entrepreneur, philanthropist, and the first female self-made millionaire in America."),
    Quote(text: "When they go low, we go high.", author: "Michelle Obama", imageName: "michelle_obama", additionalInfo: "Michelle Obama is an American attorney, author, and former First Lady of the United States."),
    Quote(text: "One day our descendants will think it incredible that we paid so much attention to things like the amount of melanin in our skin or the shape of our eyes or our gender instead of the unique identities of each of us as complex human beings.", author: "Franklin Thomas", imageName: "franklin_thomas", additionalInfo: "Franklin Thomas is an American philanthropist, lawyer, and civil rights activist."),
    Quote(text: "Racism is not an excuse to not do the best you can.", author: "Arthur Ashe", imageName: "arthur_ashe", additionalInfo: "Arthur Ashe was an American professional tennis player who became the first black player selected to the United States Davis Cup team and the only black man ever to win the singles title at Wimbledon, the US Open, and the Australian Open."),
    Quote(text: "You really can change the world if you care enough.", author: "Marian Wright Edelman", imageName: "marian_wright_edelman", additionalInfo: "Marian Wright Edelman is an American activist for children's rights."),
    Quote(text: "I've learned that you shouldn't go through life with a catcher's mitt on both hands; you need to be able to throw something back.", author: "Maya Angelou", imageName: "maya_angelou", additionalInfo: "Maya Angelou was an American poet, memoirist, and civil rights activist."),
    Quote(text: "I'm for truth, no matter who tells it. I'm for justice, no matter who it's for or against.", author: "Malcolm X", imageName: "malcolm_x", additionalInfo: "Malcolm X was an African American Muslim minister and human rights activist."),
    Quote(text: "We may encounter many defeats, but we must not be defeated.", author: "Maya Angelou", imageName: "maya_angelou", additionalInfo: "Maya Angelou was an American poet, memoirist, and civil rights activist."),
    Quote(text: "Never be limited by other people's limited imaginations.", author: "Dr. Mae Jemison", imageName: "mae_jemison", additionalInfo: "Dr. Mae Jemison is an American engineer, physician, and former NASA astronaut."),
    Quote(text: "The cost of liberty is less than the price of repression.", author: "W.E.B. Du Bois", imageName: "web_du_bois", additionalInfo: "W.E.B. Du Bois was an American sociologist, historian, civil rights activist, and author."),
    Quote(text: "I am my best work - a series of road maps, reports, recipes, doodles, and prayers from the front lines.", author: "Audre Lorde", imageName: "audre_lorde", additionalInfo: "Audre Lorde was a Caribbean-American writer, feminist, womanist, librarian, and civil rights activist."),
    Quote(text: "I refuse to accept the view that mankind is so tragically bound to the starless midnight of racism and war that the bright daybreak of peace and brotherhood can never become a reality.", author: "Martin Luther King Jr.", imageName: "martin_luther_king_jr", additionalInfo: "Martin Luther King Jr. was a prominent leader of the civil rights movement in the United States."),
    Quote(text: "If there is no struggle, there is no progress.", author: "Frederick Douglass", imageName: "frederick_douglass", additionalInfo: "Frederick Douglass was an African American social reformer, abolitionist, writer, and statesman."),
    Quote(text: "It is certain, in any case, that ignorance, allied with power, is the most ferocious enemy justice can have.", author: "James Baldwin", imageName: "james_baldwin", additionalInfo: "James Baldwin was an American novelist, playwright, essayist, poet, and activist."),
    Quote(text: "Every great dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.", author: "Harriet Tubman", imageName: "harriet_tubman", additionalInfo: "Harriet Tubman was an African American abolitionist and political activist."),
    Quote(text: "Don't wait around for other people to be happy for you. Any happiness you get you've got to make yourself.", author: "Alice Walker", imageName: "alice_walker", additionalInfo: "Alice Walker is an American novelist, short story writer, and poet."),
    Quote(text: "We may encounter many defeats, but we must not be defeated.", author: "Maya Angelou", imageName: "maya_angelou", additionalInfo: "Maya Angelou was an American poet, memoirist, and civil rights activist."),
    Quote(text: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou", imageName: "maya_angelou", additionalInfo: "Maya Angelou was an American poet, memoirist, and civil rights activist."),
    Quote(text: "I love myself when I am laughing. And then again when I am looking mean and impressive.", author: "Zora Neale Hurston", imageName: "zora_neale_hurston", additionalInfo: "Zora Neale Hurston was an African American author, anthropologist, and filmmaker."),
    Quote(text: "The cost of liberty is less than the price of repression.", author: "W.E.B. Du Bois", imageName: "web_du_bois", additionalInfo: "W.E.B. Du Bois was an American sociologist, historian, civil rights activist, and Pan-Africanist."),
    Quote(text: "If there is a book that you want to read, but it hasn't been written yet, you must be the one to write it.", author: "Toni Morrison", imageName: "toni_morrison", additionalInfo: "Toni Morrison was an American novelist, essayist, editor, and Nobel laureate in literature."),
    Quote(text: "You are your best thing.", author: "Toni Morrison", imageName: "toni_morrison", additionalInfo: "Toni Morrison was an American novelist, essayist, editor, and Nobel laureate in literature."),
    Quote(text: "Love is an endless act of forgiveness. Forgiveness is an endless act of love.", author: "bell hooks", imageName: "bell_hooks", additionalInfo: "bell hooks is an American author, feminist, and social activist."),
    Quote(text: "In a time of destruction, create something.", author: "Maxine Hong Kingston", imageName: "maxine_hong_kingston", additionalInfo: "Maxine Hong Kingston is a Chinese American author and professor emeritus at the University of California, Berkeley."),
    Quote(text: "If there's a book you really want to read, but it hasn't been written yet, then you must write it.", author: "Toni Morrison", imageName: "toni_morrison", additionalInfo: "Toni Morrison was an American novelist, essayist, editor, and Nobel laureate in literature."),
    Quote(text: "Do not bring people in your life who weigh you down. And trust your instincts... good relationships feel good. They feel right. They don't hurt.", author: "Oprah Winfrey", imageName: "oprah_winfrey", additionalInfo: "Oprah Winfrey is an American talk show host, television producer, actress, and philanthropist."),
    Quote(text: "I am my best work - a series of road maps, reports, recipes, doodles, and prayers from the front lines.", author: "Audre Lorde", imageName: "audre_lorde", additionalInfo: "Audre Lorde was an American writer, feminist, and civil rights activist."),
    Quote(text: "I had to make my own living and my own opportunity! But I made it! Don't sit down and wait for the opportunities to come. Get up and make them!", author: "Madam C.J. Walker", imageName: "madam_cj_walker", additionalInfo: "Madam C.J. Walker was an African American entrepreneur, philanthropist, and political and social activist."),
    Quote(text: "Success is not about the destination, it's about the journey.", author: "Joyce Meyer", imageName: "joyce_meyer", additionalInfo: "Joyce Meyer is an American author and speaker, and president of Joyce Meyer Ministries."),
    Quote(text: "I am my best work - a series of road maps, reports, recipes, doodles, and prayers from the front lines.", author: "Audre Lorde", imageName: "audre_lorde", additionalInfo: "Audre Lorde was an American writer, feminist, and civil rights activist."),
    Quote(text: "Caring for myself is not self-indulgence, it is self-preservation, and that is an act of political warfare.", author: "Audre Lorde", imageName: "audre_lorde", additionalInfo: "Audre Lorde was an American writer, feminist, and civil rights activist."),
    Quote(text: "I'd like people to think of me as someone who cares about them.", author: "Denzel Washington", imageName: "denzel_washington", additionalInfo: "Denzel Washington is an American actor, director, and producer."),
    Quote(text: "Excellence is the best deterrent to racism or sexism.", author: "Oprah Winfrey", imageName: "oprah_winfrey", additionalInfo: "Oprah Winfrey is an American talk show host, television producer, actress, and philanthropist."),
    Quote(text: "We should not wait for someone else to come and raise our voice. We should do it by ourselves. We should believe in ourselves.", author: "Malala Yousafzai", imageName: "malala_yousafzai", additionalInfo: "Malala Yousafzai is a Pakistani activist for female education and the youngest Nobel Prize laureate."),
    Quote(text: "I don't want to be a token. I don't want to be someone's slogan. I want to be appreciated for who I am and what I do.", author: "Misty Copeland", imageName: "misty_copeland", additionalInfo: "Misty Copeland is an American ballet dancer for the American Ballet Theatre."),
    Quote(text: "The most common way people give up their power is by thinking they don't have any.", author: "Alice Walker", imageName: "alice_walker", additionalInfo: "Alice Walker is an American novelist, short story writer, and poet."),
    Quote(text: "Love makes your soul crawl out from its hiding place.", author: "Zora Neale Hurston", imageName: "zora_neale_hurston", additionalInfo: "Zora Neale Hurston was an African American author, anthropologist, and filmmaker."),
    Quote(text: "Do the best you can until you know better. Then when you know better, do better.", author: "Maya Angelou", imageName: "maya_angelou", additionalInfo: "Maya Angelou was an American poet, memoirist, and civil rights activist."),
    Quote(text: "I don't want to be a supermodel; I want to be a role model.", author: "Naomi Campbell", imageName: "naomi_campbell", additionalInfo: "Naomi Campbell is a British model and businesswoman."),
    Quote(text: "I will not have my life narrowed down. I will not bow down to somebody else's whim or to someone else's ignorance.", author: "Bell Hooks", imageName: "bell_hooks", additionalInfo: "Bell Hooks is an American author, feminist, and social activist."),
    Quote(text: "Every great dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.", author: "Harriet Tubman", imageName: "harriet_tubman", additionalInfo: "Harriet Tubman was an African American abolitionist and political activist."),
    Quote(text: "I love myself when I am laughing. And then again when I am looking mean and impressive.", author: "Zora Neale Hurston", imageName: "zora_neale_hurston", additionalInfo: "Zora Neale Hurston was an African American author, anthropologist, and filmmaker."),
    Quote(text: "The cost of liberty is less than the price of repression.", author: "W.E.B. Du Bois", imageName: "web_du_bois", additionalInfo: "W.E.B. Du Bois was an American sociologist, historian, civil rights activist, and Pan-Africanist."),
    Quote(text: "If there is a book that you want to read, but it hasn't been written yet, you must be the one to write it.", author: "Toni Morrison", imageName: "toni_morrison", additionalInfo: "Toni Morrison was an American novelist, essayist, editor, and Nobel laureate in literature."),
    Quote(text: "You are your best thing.", author: "Toni Morrison", imageName: "toni_morrison", additionalInfo: "Toni Morrison was an American novelist, essayist, editor, and Nobel laureate in literature."),
    Quote(text: "Love is an endless act of forgiveness. Forgiveness is an endless act of love.", author: "bell hooks", imageName: "bell_hooks", additionalInfo: "bell hooks is an American author, feminist, and social activist."),
    Quote(text: "In a time of destruction, create something.", author: "Maxine Hong Kingston", imageName: "maxine_hong_kingston", additionalInfo: "Maxine Hong Kingston is a Chinese American author and professor emeritus at the University of California, Berkeley."),
    Quote(text: "If there's a book you really want to read, but it hasn't been written yet, then you must write it.", author: "Toni Morrison", imageName: "toni_morrison", additionalInfo: "Toni Morrison was an American novelist, essayist, editor, and Nobel laureate in literature."),
    Quote(text: "Do not bring people in your life who weigh you down. And trust your instincts... good relationships feel good. They feel right. They don't hurt.", author: "Oprah Winfrey", imageName: "oprah_winfrey", additionalInfo: "Oprah Winfrey is an American talk show host, television producer, actress, and philanthropist."),
    Quote(text: "I am my best work - a series of road maps, reports, recipes, doodles, and prayers from the front lines.", author: "Audre Lorde", imageName: "audre_lorde", additionalInfo: "Audre Lorde was an American writer, feminist, and civil rights activist."),
    Quote(text: "I had to make my own living and my own opportunity! But I made it! Don't sit down and wait for the opportunities to come. Get up and make them!", author: "Madam C.J. Walker", imageName: "madam_cj_walker", additionalInfo: "Madam C.J. Walker was an African American entrepreneur, philanthropist, and political and social activist."),
    Quote(text: "Success is not about the destination, it's about the journey.", author: "Joyce Meyer", imageName: "joyce_meyer", additionalInfo: "Joyce Meyer is an American author and speaker, and president of Joyce Meyer Ministries."),
    Quote(text: "I am my best work - a series of road maps, reports, recipes, doodles, and prayers from the front lines.", author: "Audre Lorde", imageName: "audre_lorde", additionalInfo: "Audre Lorde was an American writer, feminist, and civil rights activist."),
    Quote(text: "Caring for myself is not self-indulgence, it is self-preservation, and that is an act of political warfare.", author: "Audre Lorde", imageName: "audre_lorde", additionalInfo: "Audre Lorde was an American writer, feminist, and civil rights activist."),
    Quote(text: "I'd like people to think of me as someone who cares about them.", author: "Denzel Washington", imageName: "denzel_washington", additionalInfo: "Denzel Washington is an American actor, director, and producer."),
    Quote(text: "Excellence is the best deterrent to racism or sexism.", author: "Oprah Winfrey", imageName: "oprah_winfrey", additionalInfo: "Oprah Winfrey is an American talk show host, television producer, actress, and philanthropist."),
    Quote(text: "We should not wait for someone else to come and raise our voice. We should do it by ourselves. We should believe in ourselves.", author: "Malala Yousafzai", imageName: "malala_yousafzai", additionalInfo: "Malala Yousafzai is a Pakistani activist for female education and the youngest Nobel Prize laureate."),
    Quote(text: "I don't want to be a token. I don't want to be someone's slogan. I want to be appreciated for who I am and what I do.", author: "Misty Copeland", imageName: "misty_copeland", additionalInfo: "Misty Copeland is an American ballet dancer for the American Ballet Theatre."),
    Quote(text: "The most common way people give up their power is by thinking they don't have any.", author: "Alice Walker", imageName: "alice_walker", additionalInfo: "Alice Walker is an American novelist, short story writer, and poet."),
    Quote(text: "Love makes your soul crawl out from its hiding place.", author: "Zora Neale Hurston", imageName: "zora_neale_hurston", additionalInfo: "Zora Neale Hurston was an African American author, anthropologist, and filmmaker."),
    Quote(text: "Do the best you can until you know better. Then when you know better, do better.", author: "Maya Angelou", imageName: "maya_angelou", additionalInfo: "Maya Angelou was an American poet, memoirist, and civil rights activist."),
    Quote(text: "I don't want to be a supermodel; I want to be a role model.", author: "Naomi Campbell", imageName: "naomi_campbell", additionalInfo: "Naomi Campbell is a British model and businesswoman."),
]
